Repository honestbank/terraform-gcp-gke, pull requests merged in 2022-11, with the labels that each got.

#83 feat: Support creation of additional node pools
  .pre-commit-config.yaml
  Makefile
  inputs.tf
  main.tf
  makefile
  modules/gcp-gke/README.md
  modules/gcp-gke/inputs.tf
  modules/gcp-gke/main.tf
  modules/gcp-gke/modules/gcp-gke-node-pool/README.md
  modules/gcp-gke/modules/gcp-gke-node-pool/inputs.tf
  modules/gcp-gke/modules/gcp-gke-node-pool/node-pool.tf
  modules/gcp-gke/modules/gcp-gke-node-pool/outputs.tf
  modules/gcp-gke/modules/gcp-gke-node-pool/terraform.tf
  modules/gcp-gke/network.tf
  modules/gcp-gke/node-pool-tags.tf
  modules/gcp-gke/node-pools.tf
  test/gke_test.go
  test/test_helpers.go
  test/wrapper.auto.tfvars
  wrapper.auto.tfvars
Labels: size/L

#84 fix: avoid failing plan when skipping the 'primary' node pool
  modules/gcp-gke/README.md
  modules/gcp-gke/inputs.tf
  modules/gcp-gke/node-pool-tags.tf
  test/gke_test.go
  test/wrapper.auto.tfvars
  wrapper.auto.tfvars
Labels: size/S

#85 fix: read node pool from list instead of from map
  main.tf
  modules/gcp-gke/node-pool-tags.tf
Labels: size/XS
