Repository honestbank/terraform-gcp-gke, pull requests merged in 2023-05, with the labels that each got.

#105 feat: Add enable_secure_boot to enable import of prometheus node pool into TF state
  main.tf
  modules/gcp-gke/README.md
  modules/gcp-gke/inputs.tf
  modules/gcp-gke/modules/gcp-gke-node-pool/inputs.tf
  modules/gcp-gke/modules/gcp-gke-node-pool/node-pool.tf
  modules/gcp-gke/node-pools.tf
  test/wrapper.auto.tfvars
Labels: size/S

#106 feat!: added dynamic block for master_authorized_networks_config
  README.md
  inputs.tf
  main.tf
  modules/gcp-gke/README.md
  modules/gcp-gke/inputs.tf
  modules/gcp-gke/main.tf
  test/wrapper.auto.tfvars
  wrapper.auto.tfvars
Labels: size/M

#108 fix: use provided providers rather than depending on implicit provider
  modules/gcp-gke/main.tf
  modules/gcp-gke/network.tf
  modules/gcp-gke/node-pool-tags.tf
Labels: size/S

#109 fix: GKE version update to fix Terratest
  test/gke_test.go
  test/wrapper.auto.tfvars
Labels: size/XS
